upload_spreadsheet/urls.py
#!/usr/bin/env python
# coding: ascii

"""
:copyright: 2016 Matti Kariluoma <matti.kariluoma@gmail.com>
:license: CC BY-NC-ND 3.0 @see LICENSE
"""
from django.conf.urls import url
from . import views

urlpatterns = [
		url(r'^$', views.index),
		url(r'^verify-(?P<pk>[0-9]+)/locations/clean/$', views.clean_locations),
		url(r'^verify-(?P<pk>[0-9]+)/locations/add/planting-methods/$', views.add_planting_methods),
		url(r'^verify-(?P<pk>[0-9]+)/locations/add/$', views.add_locations),
		url(r'^verify-(?P<pk>[0-9]+)/locations/$', views.verify_locations),
		url(r'^verify-(?P<pk>[0-9]+)/varieties/clean/$', views.clean_varieties),
		url(r'^verify-(?P<pk>[0-9]+)/varieties/add/$', views.add_varieties),
		url(r'^verify-(?P<pk>[0-9]+)/varieties/$', views.verify_varieties),
		url(r'^verify-(?P<pk>[0-9]+)/measures/clean/$', views.clean_measures),
		url(r'^verify-(?P<pk>[0-9]+)/measures/$', views.verify_measures),
		url(r'^verify-(?P<pk>[0-9]+)/statistics/clean/$', views.clean_stats),
		url(r'^verify-(?P<pk>[0-9]+)/statistics/add/$', views.add_stats),
		url(r'^verify-(?P<pk>[0-9]+)/statistics/$', views.verify_stats),
		url(r'^verify-(?P<pk>[0-9]+)/preview/$', views.verify_preview),
		url(r'^verify-(?P<pk>[0-9]+)/$', views.verify),
		url(r'^update-(?P<pk>[0-9]+)/$', views.update),
	]

variety_trials_website/urls.py
#!/usr/bin/env python
# coding: ascii

"""
:copyright: 2012 Matti Kariluoma <matti.m.kariluoma@ndsu.edu>
:license: CC BY-NC-ND 3.0 @see LICENSE
"""
from django.conf.urls import include, url, handler404
from django.conf import settings
from django.contrib import admin
from variety_trials_data.models import *
from variety_trials_data import views
#from variety_trials_data import json_views
from nopasswordauth import views as authviews

handler404 = authviews.page_not_found

urlpatterns = [
		#url(r'^admin/login/', authviews.login),
		#url(r'^admin/', include(admin.site.urls)),
		#url(r'^accounts/login/', authviews.login),
		#url(r'^accounts/', include('nopassword.urls')),
		#url(r'^upload/', include('upload_spreadsheet.urls')),
		
		url(r'^$', views.index), # the home page
		
		url(r'^about/', views.about),
		
		url(r'^view/$', views.advanced_search),
		url(r'^view/last_(?P<year_range>[0-9]+)_years/(?P<fieldname>[a-z0-9_]+)/', views.zipcode_view), # defaults to location-based view
		url(r'^view/(?P<startyear>[0-9]+)/(?P<fieldname>[a-z0-9_]+)/', views.historical_zipcode_view), # defaults to location-based view
		#url(r'^view/variety/(?P<variety_name>[a-zA-Z_]+)/', views.variety_info),
		#url(r'^view/available/', views.inspect),
]

'''
		url(r'^data/$', views.howto_api),
		url(r'^data/trial_entry/id_(?P<id>[0-9]+)/json/', json_views.trial_entry_json),
		url(r'^data/trial_entry/near_zipcode_(?P<zipcode>[0-9]+)/last_3_years/json/', json_views.trial_entry_near_json),
		url(r'^data/trial_entry/near_zipcode_(?P<zipcode>[0-9]+)/last_3_years/ids/json/', json_views.trial_entry_near_ids_json),
		url(r'^data/zipcode/id_(?P<id>[0-9]+)/json/', json_views.zipcode_json),
		url(r'^data/zipcode/partial_zipcode_(?P<partial_zipcode>[0-9]+)/json/', json_views.autocomplete_zipcode_json),
		url(r'^data/location/id_(?P<id>[0-9]+)/json/', json_views.location_json),
		url(r'^data/location/all/json/', json_views.location_json_all),
		url(r'^data/location/near_zipcode_(?P<zipcode>[0-9]+)/json/', json_views.zipcode_near_json),
		url(r'^data/variety/all/json/', json_views.variety_json_all),
		url(r'^data/variety/id_(?P<id>[0-9]+)/json/', json_views.variety_json),
		url(r'^data/disease/id_(?P<id>[0-9]+)/json/', json_views.disease_json),
		'''

upload_spreadsheet/forms.py
#!/usr/bin/env python
# coding: ascii

"""
:copyright: 2016 Matti Kariluoma <matti.kariluoma@gmail.com>
:license: CC BY-NC-ND 3.0 @see LICENSE
"""
from django import forms
from variety_trials_data import models # TODO: reduce this cross-module coupling
from variety_trials_data import variety_trials_forms as hrsw_forms
from . import progress
import datetime

class Upload(forms.Form):
	data_json = forms.CharField(
			widget = forms.Textarea,
			required = False,
			help_text = 'data from javascript view',
		)
	data = forms.CharField(
			widget = forms.Textarea,
			required = False,
			help_text = 'data from noscript view',
		)

class VerifyHeaders(forms.Form):
	header_type = forms.ChoiceField(
			choices=[
					(progress.HeaderTypes.Data, '--'),
					(progress.HeaderTypes.Locations, progress.HeaderTypes.Locations),
					(progress.HeaderTypes.Varieties, progress.HeaderTypes.Varieties),
					(progress.HeaderTypes.Measures, progress.HeaderTypes.Measures),
				],
			label='type',
		)

class DateForm(forms.Form):
	now = lambda: datetime.datetime.now().year
	year = forms.ChoiceField(
			choices=[(x, x) for x in [now() + (i-18) for i in range(21)]], 
			label='Which year is this data for?',
		)

class VerifyLocation(forms.Form):
	location = forms.ModelChoiceField(
			models.Location.objects.all(),
			empty_label='Not Listed',
		)
	planting_methods = forms.ModelChoiceField(
			models.PlantingMethod.objects.all(),
			empty_label='Not Listed',
			required=False,
		)
	is_not = forms.BooleanField(
			required=False,
			label='This is not a Location',
		)
	is_stat = forms.BooleanField(
			required=False,
			label='This is a statistical measure',
		)

class VerifyVariety(forms.Form):
	variety = forms.ModelChoiceField(
			models.Variety.objects.all(),
			empty_label='Not Listed',
		)
	is_not = forms.BooleanField(
			required=False,
			label='This is not a Variety',
		)
	is_stat = forms.BooleanField(
			required=False,
			label='This is a statistical measure',
		)

class VerifyMeasure(forms.Form):
	mchoices = [(x, x) for x in models.TrialEntry.measures]
	measure = forms.ChoiceField(choices=mchoices)
	is_not = forms.BooleanField(
			required=False,
			label='This is not a Measure',
		)
	is_stat = forms.BooleanField(
			required=False,
			label='This is a statistical (aggregate) measure',
		)

class VerifyStatistic(forms.Form):
	mchoices = [(x, x) for x in models.TrialEntry.measures]
	measure = forms.ChoiceField(
			choices=mchoices,
			label='This statistic compares',
		)
	schoices = [(x, x) for x in models.SignificanceEntry.methods]
	statistic = forms.ChoiceField(choices=schoices)
	lchoices = [(x, x) for x in models.SignificanceEntry.levels]
	alpha = forms.ChoiceField(
			required=False,
			choices=lchoices,
			label='Alpha level',
		)
	is_not = forms.BooleanField(
			required=False,
			label='These data are not one of the listed statistics',
		)

class AddLocation(hrsw_forms.NewLocation):
	is_not = forms.BooleanField(
			required=False,
			label='This is not a Location',
		)
	is_stat = forms.BooleanField(
			required=False,
			label='This is a statistical measure',
		)

class AddVariety(hrsw_forms.NewVariety):
	is_not = forms.BooleanField(
			required=False,
			label='This is not a Variety',
		)
	is_stat = forms.BooleanField(
			required=False,
			label='This is a statistical measure',
		)

class AddPlantingMethod(hrsw_forms.NewPlantingMethod):
	is_not = forms.BooleanField(
			required=False,
			label='There is not a Planting Method in this name',
		)
	is_stat = forms.BooleanField(
			required=False,
			label='This is a statistical measure',
		)
		
class AddStatistic(Upload):
	is_not = forms.BooleanField(
			required=False,
			label='These data are not one of the listed statistics',
		)

upload_spreadsheet/views.py
#!/usr/bin/env python
# coding: ascii

"""
:copyright: 2016 Matti Kariluoma <matti.kariluoma@gmail.com>
:license: CC BY-NC-ND 3.0 @see LICENSE
"""
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from django.template import Template, loader, RequestContext
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from django import forms as django_forms
from common.util import restricted
from . import forms, models, utils
from progress import Progress, HeaderTypes, HeaderGuess
import json, datetime

@restricted
def index(request):
	context = {}
	uploads = models.UploadProgress.objects.filter(user=request.user)
	in_progress = uploads.filter(submitted=False)
	submitted = sorted(uploads.filter(submitted=True), key=lambda item: item.created)
	if request.method == 'POST':
		completed_form = forms.Upload(request.POST)
		if not completed_form.is_valid():
			return HttpResponse("There was a problem with your submission. Please go back and try again.")
		data_json = utils.process_upload_form(completed_form)
		if not data_json:
			return HttpResponse("You submitted an empty spreadsheet. Please go back and try again.")
		try:
			username = getattr(request.user, request.user.USERNAME_FIELD)
		except:
			username = 'None'
		path = '{username}_{count}.json'.format(username=username, count=uploads.count())
		path = default_storage.save(path, ContentFile(data_json))
		new_progress = models.UploadProgress(user=request.user, path=path)
		new_progress.save()
	in_progress = sorted(in_progress, key=lambda item: item.created)
	context['in_progress'] = in_progress
	context['submitted'] = submitted
	return render(request, 'upload.html', context)

@restricted
def verify(request, pk=None):
	try:
		in_progress = models.UploadProgress.objects.get(pk=pk)
	except:
		raise Http404
	context = {}
	progress = Progress(in_progress)
	if request.method == 'POST':
		row_form = forms.VerifyHeaders(request.POST, prefix=HeaderGuess.ROW_PREFIX)
		col_form = forms.VerifyHeaders(request.POST, prefix=HeaderGuess.COLUMN_PREFIX)
		dateform = forms.DateForm(request.POST)
		if not dateform.is_valid():
			return redirect('.') # TODO: Let user know dateform was invalid
		if row_form.is_bound and row_form.is_valid():
			row_type = row_form.cleaned_data['header_type']
		else:
			row_type = HeaderTypes.Data
		if col_form.is_bound and col_form.is_valid():
			col_type = col_form.cleaned_data['header_type']
		else:
			col_type = HeaderTypes.Data
		progress.store_date(dateform, save=False)
		progress.store_headers(row_type, col_type)
		if progress.dates_verified():
			return redirect('locations/')
		else:
			return redirect('.') # TODO: Let user know date was unverified
	else:
		col_guess, row_guess = progress.header_guesses()
		verify_dicts = []
		for guess in (col_guess, row_guess):
			if guess.our_guess() is None or not any(guess.users_input()):
				continue
			form = forms.VerifyHeaders(
					initial={'header_type': guess.our_guess()},
					prefix=guess.prefix
				)
			verify_dicts.append({'headers': guess.users_input(), 'form': form})
		context['verify_dicts'] = verify_dicts
		now_year = datetime.datetime.now().year
		context['dateform'] = forms.DateForm(initial={'year': now_year})
	return render(request, 'verify.html', context)

def verify_model_list(request, progress, template=None, Formcls=None, 
		create_initial_form=None, create_single_form=None, model_names=None, 
		map_name=None, is_verified=None, next_url=None, guesses=None
	):
	if create_single_form is None:
		create_single_form = lambda Fcls, prefix: Fcls(prefix=prefix)
	context = {}
	if request.method == 'POST':
		if 'single_model' in request.POST:
			form = Formcls(
					request.POST, 
					prefix='_whip_single'
				)
			if form.is_bound and form.is_valid():
				map_name(None, form)
		else:
			unsaved = False
			for name in list(model_names):
				form = Formcls(
						request.POST,
						prefix=name
					)
				if not form.is_bound:
					continue
				valid = form.is_valid()
				# try and grab some data in any case
				try:
					is_not = form.cleaned_data['is_not']
				except KeyError:
					is_not = False
				try:
					is_stat = form.cleaned_data['is_stat']
				except KeyError:
					is_stat = False
				if not valid:
					form = None # discard remainder of form
				if is_not or is_stat:
					map_name(name, None, delete=True, save=True)
				if is_stat:
					progress.add_statistic(name, save=True)
				if not is_not and not is_stat:
					map_name(name, form, save=False)
					unsaved = True
			if unsaved:
				progress.save()
		if is_verified():
			return redirect(next_url)
		else:
			return redirect('add/')
	else:
		verify_dicts = []
		for guess in guesses():
			form = create_initial_form(Formcls, guess)
			headers, values = [], []
			try:
				cells = list(progress.progress['cells'][guess.users_input()])
				cells[0] = ('', cells[0][1]) # blank first item
			except KeyError:
				cells = []
			for h, v in cells:
				headers.append(h)
				values.append(v)
			verify_dicts.append({
					'name': guess.users_input(), 
					'form': form,
					'headers': headers,
					'values': values,
				})
		context['verify_dicts'] = verify_dicts
		single_form = create_single_form(Formcls, '_whip_single')
		single_form.fields['is_not'].widget = django_forms.HiddenInput()
		context['single_form'] = single_form
		context['preview'] = progress.progress['cells']
	return render(request, template, context)

@restricted
def verify_locations(request, pk=None):
	try:
		in_progress = models.UploadProgress.objects.get(pk=pk)
	except:
		raise Http404
	progress = Progress(in_progress)
	def create_location_form(Formcls, guess):
		initial = {
				'location': guess.our_guess(), 
				'planting_methods': guess.extra['planting_methods']
			}
		return Formcls(initial=initial, prefix=guess.users_input())
	return verify_model_list(
			request,
			progress,
			template='verify-locations.html',
			Formcls=forms.VerifyLocation,
			create_initial_form=create_location_form,
			model_names=progress.locations(),
			map_name=progress.map_location,
			is_verified=progress.locations_verified,
			next_url='../varieties/',
			guesses=progress.location_guesses,
		)
@restricted
def verify_varieties(request, pk=None):
	try:
		in_progress = models.UploadProgress.objects.get(pk=pk)
	except:
		raise Http404
	progress = Progress(in_progress)
	def create_variety_form(Formcls, guess):
		initial = {'variety': guess.our_guess(), }
		return Formcls(initial=initial, prefix=guess.users_input())
	return verify_model_list(
			request,
			progress,
			template='verify-varieties.html',
			Formcls=forms.VerifyVariety,
			create_initial_form=create_variety_form,
			model_names=progress.varieties(),
			map_name=progress.map_variety,
			is_verified=progress.varieties_verified,
			next_url='../measures/',
			guesses=progress.variety_guesses,
		)
@restricted
def verify_measures(request, pk=None):
	try:
		in_progress = models.UploadProgress.objects.get(pk=pk)
	except:
		raise Http404
	progress = Progress(in_progress)
	def create_measure_form(Formcls, guess):
		initial = {'measure': guess.our_guess(), }
		return Formcls(initial=initial, prefix=guess.users_input())
	return verify_model_list(
			request,
			progress,
			template='verify-measures.html',
			Formcls=forms.VerifyMeasure,
			create_initial_form=create_measure_form,
			model_names=progress.measures(),
			map_name=progress.map_measure,
			is_verified=progress.measures_verified,
			next_url='../statistics/',
			guesses=progress.measure_guesses,
		)
@restricted
def verify_stats(request, pk=None):
	try:
		in_progress = models.UploadProgress.objects.get(pk=pk)
	except:
		raise Http404
	progress = Progress(in_progress)
	def create_statistic_form(Formcls, guess):
		initial = {
				'statistic': guess.our_guess(), 
				'alpha': guess.extra['alpha'],
			}
		return Formcls(initial=initial, prefix=guess.users_input())
	return verify_model_list(
			request,
			progress,
			template='verify-stats.html',
			Formcls=forms.VerifyStatistic,
			create_initial_form=create_statistic_form,
			model_names=progress.statistics(),
			map_name=progress.map_statistic,
			is_verified=progress.statistics_verified,
			next_url='../preview/',
			guesses=progress.statistic_guesses,
		)
@restricted
def verify_preview(request, pk=None):
	try:
		in_progress = models.UploadProgress.objects.get(pk=pk)
	except:
		raise Http404
	progress = Progress(in_progress)
	context = {}
	if request.method == 'POST':
		progress.write_database()
		return redirect('../../')
	else:
		if not progress.dates_verified():
			return redirect('../')
		if not progress.locations_verified():
			return redirect('../locations/')
		if not progress.varieties_verified():
			return redirect('../varieties/')
		if not progress.measures_verified():
			return redirect('../measures/')
		if not progress.statistics_verified():
			return redirect('../statistics/')
		year, table, summary, statnames, colnames, rownames = progress.prepare_table()
		preview_table = zip(rownames, table)
		preview_summary = zip(statnames, summary)
		context['year'] = year
		context['preview_table'] = preview_table
		context['preview_summary'] = preview_summary
		context['column_headers'] = ['', ] + colnames
	return render(request, 'verify-preview.html', context)

def add_model(request, progress, unknown_names=None, template=None, 
		Formcls=None, form_fieldname=None, input_fieldname=None,
		map_name=None, is_verified=None, next_url='..', model_cache=None
	):
	context = {}
	if request.method == 'POST':
		unsaved = False
		for name in unknown_names:
			form = Formcls(
					request.POST,
					prefix=name
				)
			if form.is_bound and form.is_valid():
				user_input = form.cleaned_data[input_fieldname]
				try:
					model = model_cache[user_input]
				except KeyError:
					model = form.save()
					model_cache[user_input] = model
				form.cleaned_data[form_fieldname] = model
				map_name(name, form, save=False)
				unsaved = True
			else:

upload_spreadsheet/templates/add-locations.html
{% load i18n %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>{% trans "Add Locations to Database" %}</title>
</head>
<body>

<h2>{% trans "Add new locations to the database" %}</h2>
<p>{% trans "Please answer the following questions" %}:</p>
<p>{% trans "The wikipedia article for a city usually lists its zipcode in the sidebar. If this location is not a city, please select the nearest city and use its zipcode." %}</p>
<p>{% trans "Planting methods that were marked as Not Listed will be filled out on the next page." %}</p>
<form method="post" class="form-vertical" id="spreadsheet_form">
	{% csrf_token %}
<ul>
{% for add_model_dict in add_model_dicts %}
	<li>
	{% if add_model_dict.name %}
	        {% trans "You input" %} "{{ add_model_dict.name }}".
	{% else %}
		{% trans "There are no Locations listed on your spreadsheet. If this spreadsheet is data for a single location, enter its name below. Otherwise, go back and indicate which list of names are Locations." %}
	{% endif %}
	{% trans "This is the Location" %}:
		<ul><li>{{ add_model_dict.form }}</li></ul>
	</li>
{% empty %}
	<li>{% trans "We couldn't find any locations on your spreadsheet that aren't already in the database. If you are constantly being redirected to this page, please contact your system administrator." %}</li>
{% endfor %}
</ul>
	<button id="submit" type="submit" class="btn">{% trans "Submit" %}</button>
</form>
</body>
</html>

upload_spreadsheet/templates/add-planting-methods.html
{% load i18n %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>{% trans "Add Planting Methods to Database" %}</title>
</head>
<body>

<h2>{% trans "Add new planting methods to the database" %}</h2>
<p>{% trans "Please answer the following questions" %}:</p>
<p>{% trans "Planting Methods are a series of keywords, separated by commas." %}</p>
<p>{% trans "Note: If there are no special planting methods for a location, just leave the form input blank." %}</p>
<form method="post" class="form-vertical" id="spreadsheet_form">
	{% csrf_token %}
<ul>
{% for dict in add_model_dicts %}
        <li>
	{% if dict.name %}
                {% trans "You input" %} "{{ dict.name }}".
	{% else %}
		{% trans "If this location uses a planting method that wasn't listed, please enter it below. If there was no special planting method, leave the form input blank and click submit." %}
        {% endif %}
	{% trans "This indicates the planting method tags were used at this location" %}:
		<ul>
			<li>{{ dict.form }}</li>
		</ul>
	</li>
{% empty %}
	<li>{% trans "We couldn't find any planting methods/locations on your spreadsheet that aren't already in the database. If you are constantly being redirected to this page, please contact your system administrator." %}</li>
{% endfor %}
</ul>
	<button id="submit" type="submit" class="btn">{% trans "Submit" %}</button>
</form>
</body>
</html>

upload_spreadsheet/templates/add-varieties.html
{% load i18n %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>{% trans "Add Varieties/Cultivars to Database" %}</title>
</head>
<body>

<h2>{% trans "Add new varieties/cultivars to the database" %}</h2>
<p>{% trans "Please answer the following questions" %}:</p>
<form method="post" class="form-vertical" id="spreadsheet_form">
	{% csrf_token %}
<ul>
{% for add_model_dict in add_model_dicts %}
	<li>
	{% if add_model_dict.name %}
                {% trans "You input" %} "{{ add_model_dict.name }}".
        {% else %}
                {% trans "There are no Varieties listed on your spreadsheet. If this spreadsheet is for a single variety, fill out the form below. Otherwise, go back and select the list of names that are Varieties." %}
        {% endif %}
	{% trans "This is the Variety" %}:
		<ul><li>{{ add_model_dict.form }}</li></ul>
	</li>
{% empty %}
	<li>{% trans "We couldn't find any varieties on your spreadsheet that aren't already in the database. If you are constantly being redirected to this page, please contact your system administrator." %}</li>
{% endfor %}
</ul>
	<button id="submit" type="submit" class="btn">{% trans "Submit" %}</button>
</form>
</body>
</html>

upload_spreadsheet/templates/clean.html
{% load i18n %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>{% trans "Clean Previous Input" %}</title>
</head>
<body>

<h2>{% trans "Clean Previous Input" %}</h2>
<p>{% trans "If you've previously entered incorrect data and can't get this application to work properly, click Clean below to remove all traces of old entries. Your original spreadsheet will not be touched. You will then be sent to reenter the data." %}:</p>
<form method="post" class="form-vertical" id="spreadsheet_form">
	{% csrf_token %}
	<button id="submit" type="submit" class="btn">{% trans "Clean" %}</button>
</form>
</body>
</html>

upload_spreadsheet/templates/upload.html
{% load i18n %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>{% trans "Upload" %}</title>
	<!-- thanks https://github.com/handsontable/handsontable -->
	<script src="{% static "handsontable.full.min.js" %}"></script>
	<link rel="stylesheet" media="screen" href="{% static "handsontable.full.min.css" %}">
</head>
<body>
<h2>{% trans "Uploads in progress" %}...</h2>
{% for progress in in_progress %}
	<a href="verify-{{progress.pk}}/">
	<p>Verify data for {{ progress.path }} created {{ progress.created }} </p>
	</a>
{% empty %}
	<p>{% trans "No uploads have been started." %}</p>
{% endfor %}

<h2>{% trans "Uploads submitted" %}</h2>
{% for progress in submitted %}
	<a href="update-{{progress.pk}}/">
	<p>Update {{ progress.path }} created {{ progress.created }}</p>
	</a>
{% empty %}
	<p>{% trans "No uploads have been finished and submitted." %}</p>
{% endfor %}

<h2>{% trans "Begin a new upload" %}</h2>
<p>{% trans "Upload your data by copying it from a spreadsheet and pasting it below." %}</p>
<form method="post" class="form-vertical" id="spreadsheet_form">
	{% csrf_token %}
	<div id="spreadsheet_data" class="control-group row-fluid" style="width: 55em; height: 300px;">
<noscript>
		<label for="id_data">Data:</label>
		<textarea id="id_data" name="data"></textarea>
</noscript>
		<textarea id="spreadsheet_data_text" name="data_json" style="display: none;"></textarea>
	</div>
	<div class="controls">
<noscript>
		<button id="submit" type="submit" class="btn">{% trans "Upload" %}</button>
</noscript>
		<button id="spreadsheet_submit" type="button" class="btn" style="display: none;">{% trans "Upload" %}</button>
	</div>
</form>
<script>
	var container = document.getElementById('spreadsheet_data');
	container.style.overflow = 'hidden'; // show scroll-bars
	var options = {
			rowHeaders: true,
			colHeaders: true,
			stretchH: 'all',
			minSpareRows: 2,
			minSpareCols: 2,
			contextMenu: true,
		};
	var hot = new Handsontable(container, options);
	var submit = document.getElementById('spreadsheet_submit');
	submit.style.display = ''; // visible
	Handsontable.Dom.addEvent(submit, 'click', function()
			{
				var textarea = document.getElementById('spreadsheet_data_text');
				textarea.value = JSON.stringify({data: hot.getData()});
				var form = document.getElementById('spreadsheet_form');
				form.submit();
			}
		);
	
</script>
</body>
</html>

upload_spreadsheet/templates/verify-locations.html
{% load i18n %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>{% trans "Verify - 2 / 6" %}</title>
</head>
<body>

<h2>{% trans "Step 2 of 6: Match input location names with known locations" %}</h2>
<p>{% trans "If the location name isn't present, please select 'Not Listed'. The system will help you create location entries for anything marked 'Not Listed'. " %}</p>
<p>{% trans "Please answer the following questions" %}:</p>
<form method="post" class="form-vertical" id="spreadsheet_form">
	{% csrf_token %}
{% if verify_dicts %}
	<h3>{% trans "Multiple Locations" %}</h3>
{% else %}
	<h3>{% trans "Single Location" %}</h3>
{% endif %}
{% for verify_dict in verify_dicts %}
        <p>You input "{{ verify_dict.name }}".</p>
        <table>
					<tr class="location">
{% for header in verify_dict.headers %}
					<th>{{ header }}</th>
{% endfor %}
					</tr>
					<tr>
{% for value in verify_dict.values %}
					<td>{{ value }}</td>
{% endfor %}
					</tr>
        </table>
        <p>This is {{ verify_dict.form }}</p>
{% empty %}
	<p>{% trans "We couldn't find any location info on your spreadsheet." %}</p>
	<p>{% trans "If this data is for a single location, please fill out the following:" %}</p>
	{{ single_form }}
	<input type="hidden" name="single_model" value="single_model">
{% endfor %}
	<button id="submit" type="submit" class="btn">{% trans "Submit" %}</button>
</form>
{% if not verify_dicts %}
	<h3>{% trans "Multiple Locations" %}</h3>
	<p>
	{% trans "If this data is for multiple locations, do not continue. When copying data into the " %}
	<a href="../../">{% trans "upload form" %}</a>
	{% trans " please ensure the locations' names are copied as well. You will need to start over with a new upload. Sorry!" %}
	</p>
{% endif %}
<h3>{% trans "Having Problems?" %}</h3>
<p>
	{% trans "If you are having problems with this form, first try to " %}
	<a href="clean/">{% trans "clean" %}</a>
	{% trans " any data previously entered. If the problem persists, please contact the site administrator." %}
</p>
</body>
</html>